import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import type { Map as LibreMap } from 'maplibre-gl';
import 'maplibre-gl/dist/maplibre-gl.css';
import './style.css';

type Project = {id:string;name:string;site_key:string;synthetic:boolean;verified_bounds_wgs84:[number,number,number,number]|null};
type Dataset = {id:string;name:string;kind:string;version:number;sha256:string;provenance:{status:string;units:string};inspection:{issues:{code:string;message:string}[]}};
type Readiness = {missing:{code:string;message:string}[];warnings:{code:string;message:string}[]};
type Scenario = {id:string;name:string;sha256:string;snapshot:{input_mode:string}};
type Job = {id:string;state:string;body:{result?:Readiness}};
type Engine = {engine:'dflowfm'|'dualsphysics';available:boolean;reason?:string;image_id?:string};
type NumericalRun = {id:string;state:string;input:{request:{engine:string;case_kind:string}};result:{error?:string;reason?:string;normalization?:{frames:number;cells:number;duration_seconds:number}}};
async function api<T>(path:string, init?:RequestInit):Promise<T> {
  const r=await fetch('/api'+path,init); const data=await r.json();
  if(!r.ok) throw new Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));
  return data;
}
const metadataTemplate={name:'',kind:'hydrology',provenance:{source_url:'',agency:'',licence:'',acquisition_date:null,acquisition_date_note:'Acquisition period must be verified from source',units:'m3/s',crs:null,vertical_reference:null,processing_history:[],status:'observed',synthetic:false},hydro:{station_id:'',source_timezone:null,measurement:'unknown',identity_reference:null,interval_seconds:3600}};
const scenarioTemplate={name:'New release scenario',forcing:{mode:'prescribed_release',historical:true,hydrograph_dataset_id:null},dataset_ids:[],start_time:'2025-01-01T00:00:00+05:30',end_time:'2025-01-02T00:00:00+05:30',time_step_seconds:1,output_interval_seconds:60,wet_threshold_m:0.01,arrival_threshold_m:0.1,initial_river_state:null,downstream_boundary:null,tributary_inflows:null,structure_treatment:null,roughness:null,assumptions:[]};

function DomainMap({project}:{project:Project}) {
 const container=useRef<HTMLDivElement>(null);
 useEffect(()=>{
  if(!container.current||!project.verified_bounds_wgs84)return;
  const [w,s,e,n]=project.verified_bounds_wgs84;
  let map:LibreMap|undefined;let disposed=false;
  import('maplibre-gl').then(lib=>{
   if(disposed||!container.current)return;
   const instance=new lib.Map({container:container.current,style:{version:8,sources:{},layers:[{id:'background',type:'background',paint:{'background-color':'#e1eeeb'}}]},bounds:[[w,s],[e,n]],fitBoundsOptions:{padding:40}});map=instance;
   instance.on('load',()=>{instance.addSource('domain',{type:'geojson',data:{type:'Feature',properties:{},geometry:{type:'Polygon',coordinates:[[[w,s],[e,s],[e,n],[w,n],[w,s]]]}}});instance.addLayer({id:'domain',type:'line',source:'domain',paint:{'line-color':'#128477','line-width':3}});});
   instance.addControl(new lib.NavigationControl());
  });
  return()=>{disposed=true;map?.remove();};
 },[project]);
 return <div className="domain" ref={container}>{!project.verified_bounds_wgs84&&<div className="domain-empty"><span className="crosshair">⌖</span><h3>A domain starts with evidence.</h3><p>The downstream reach is awaiting terrain, structure and station review. No flood or study boundary has been drawn.</p><span className="tag">DOMAIN NOT VERIFIED</span></div>}</div>;
}

function App(){
 const [projects,setProjects]=useState<Project[]>([]),[selected,setSelected]=useState(''),[tab,setTab]=useState('Overview');
 const [datasets,setDatasets]=useState<Dataset[]>([]),[scenarios,setScenarios]=useState<Scenario[]>([]),[readiness,setReadiness]=useState<Readiness|null>(null),[jobs,setJobs]=useState<Job[]>([]),[runs,setRuns]=useState<NumericalRun[]>([]);
 const [health,setHealth]=useState<{database:string;preview:boolean;engines:Engine[]}|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[engineChoice,setEngineChoice]=useState<'dualsphysics'|'dflowfm'>('dualsphysics');
 const [metadata,setMetadata]=useState(JSON.stringify(metadataTemplate,null,2)),[scenario,setScenario]=useState(JSON.stringify(scenarioTemplate,null,2)),[file,setFile]=useState<File|null>(null);
 const project=projects.find(p=>p.id===selected);
 async function refresh(id=selected){if(!id)return;const [d,s,r,j,n]=await Promise.all([api<Dataset[]>(`/projects/${id}/datasets`),api<Scenario[]>(`/projects/${id}/scenarios`),api<Readiness>(`/projects/${id}/readiness`),api<Job[]>(`/projects/${id}/jobs`),api<NumericalRun[]>(`/projects/${id}/runs`)]);setDatasets(d);setScenarios(s);setReadiness(r);setJobs(j);setRuns(n);}
 async function act(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(String(e));}finally{setBusy(false);}}
 useEffect(()=>{Promise.all([api<Project[]>('/projects'),api<{database:string;preview:boolean;engines:Engine[]}>('/health')]).then(([p,h])=>{setProjects(p);setSelected(p[0]?.id??'');setHealth(h);}).catch(e=>setError(String(e)));},[]);
 useEffect(()=>{refresh(selected).catch(e=>setError(String(e)));},[selected]);
 useEffect(()=>{if(!jobs.some(j=>['QUEUED','RUNNING'].includes(j.state))&&!runs.some(r=>['QUEUED','RUNNING'].includes(r.state)))return;const timer=setInterval(()=>refresh().catch(e=>setError(String(e))),1500);return()=>clearInterval(timer);},[jobs,runs,selected]);
 async function upload(){if(!file)throw new Error('Choose a data file first');JSON.parse(metadata);await api(`/projects/${selected}/datasets?filename=${encodeURIComponent(file.name)}&metadata_json=${encodeURIComponent(metadata)}`,{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file});await refresh();setNotice('Source saved as a new immutable version. Review its findings before modelling.');}
 async function saveScenario(){await api(`/projects/${selected}/scenarios`,{method:'POST',headers:{'Content-Type':'application/json'},body:scenario});await refresh();setNotice('Scenario snapshot saved. Missing inputs remain visible in its audit.');}
 async function openLaboratory(){const existing=projects.find(p=>p.synthetic&&p.site_key==='laboratory-examples');if(existing){setSelected(existing.id);return;}const p=await api<Project>('/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'DamSafe laboratory examples',site_key:'laboratory-examples',synthetic:true,description:'Official engine examples only; no Ujjani predictions'})});setProjects([...projects,p]);setSelected(p.id);}
 async function submitNumerical(){await api(`/projects/${selected}/runs`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({engine:engineChoice,case_kind:'OFFICIAL_EXAMPLE',idempotency_key:crypto.randomUUID().replaceAll('-','')})});await refresh();setNotice('Official laboratory example queued. Execution success is separate from scientific validation.');}
 return <div className="shell"><aside><a className="brand" href="/">◈ <span>DamSafe</span></a><div className="eyebrow">MODELLING WORKSPACE</div><nav>{['Overview','Data library','Scenarios','Readiness','Numerical runs'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}<span>↗</span></button>)}</nav><div className="sidebar-foot"><span className="dot"/> Local development<br/><small>SIH PS 26161 · Phase 02</small></div></aside>
 <main><header><div>PROJECT / <strong>UJJANI–BHIMA</strong></div><span className="tag">{health?.preview?'SQLITE PREVIEW':'POSTGIS'}</span></header><div className="content"><div className="title-row"><div><div className="eyebrow">TRACEABLE INPUTS. EXPLAINABLE SCENARIOS.</div><h1>{tab==='Overview'?'Before the first Ujjani simulation.':tab}</h1><p className="intro">Prepare the Ujjani–Bhima case with a clear record of what is known, assumed and still missing.</p></div><select aria-label="Project" value={selected} onChange={e=>setSelected(e.target.value)}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}{p.synthetic?' · SYNTHETIC':''}</option>)}</select></div>
 {error&&<div role="alert" className="alert error">{error}</div>}{notice&&<div role="status" className="alert">{notice}</div>}
 {!project?<div className="panel">No project is configured. Run the documented bootstrap command to create the Ujjani workspace.</div>:<>
 {project.synthetic&&<div className="alert">SYNTHETIC EXAMPLE — these inputs do not represent Ujjani.</div>}
 {tab==='Overview'&&<><div className="stats"><div><label>IMPORTED SOURCES</label><strong>{datasets.length.toString().padStart(2,'0')}</strong><small>Versioned with source checksums</small></div><div><label>READINESS FINDINGS</label><strong>{readiness?.missing.length??'—'}</strong><small>Items requiring evidence or setup</small></div><div><label>UJJANI NUMERICAL RUN</label><strong className="word">Blocked</strong><small>Site mesh and physical boundary evidence missing</small></div></div><div className="overview-grid"><section className="panel"><div className="panel-heading"><h2>Study domain</h2><span className="tag">BHIMA RIVER</span></div><DomainMap project={project}/><div className="caption">MapLibre · WGS84 display · No Ujjani simulated results available</div></section><section className="panel next"><div className="eyebrow">NEXT STEPS</div><h2>Build the evidence base.</h2><ol><li><strong>Import physical inputs</strong><p>Terrain, channel geometry and timestamped water records.</p></li><li><strong>Resolve readiness findings</strong><p>Check units, elevation references, coverage and measurement meaning.</p></li><li><strong>Save a scenario</strong><p>Freeze sources and assumptions before a numerical run.</p></li></ol><button className="primary" onClick={()=>setTab('Data library')}>Open data library →</button></section></div><div className="note">No validated Ujjani flood prediction exists in this workspace. Hypothetical failure scenarios and historical releases have separate input contracts.</div></>}
 {tab==='Data library'&&<><section className="panel"><h2>Source register</h2>{!datasets.length?<p className="empty">No sources imported. Missing data is not interpreted as zero.</p>:<div className="table-wrap"><table><thead><tr><th>Source</th><th>Type</th><th>Units</th><th>Evidence</th><th>Findings</th></tr></thead><tbody>{datasets.map(d=><tr key={d.id}><td>{d.name}<small>Version {d.version} · {d.id}</small></td><td>{d.kind}</td><td>{d.provenance.units}</td><td>{d.provenance.status}</td><td>{d.inspection.issues.length}</td></tr>)}</tbody></table></div>}</section><section className="panel form"><h2>Import a source</h2><p>GeoTIFF terrain, hydrology CSV, or GeoJSON/GeoPackage vectors. Maximum 64 MiB per file. Metadata is required; unknown references stay unresolved.</p><label>Data file<input type="file" accept=".csv,.tif,.tiff,.geojson,.gpkg" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><details open><summary>Source metadata · JSON contract</summary><textarea aria-label="Source metadata" spellCheck={false} value={metadata} onChange={e=>setMetadata(e.target.value)}/></details><p>For vectors remove <code>hydro</code>, set kind and CRS. For terrain use units <code>m</code> and declare its elevation reference. Never infer missing source metadata.</p><button className="primary" disabled={busy} onClick={()=>act(upload)}>{busy?'Checking source…':'Import and inspect'}</button></section></>}
 {tab==='Scenarios'&&<><section className="panel"><h2>Immutable snapshots</h2>{!scenarios.length?<p className="empty">No scenarios saved. Draft examples below are editable software defaults, not Ujjani parameters.</p>:scenarios.map(s=><div className="scenario" key={s.id}><strong>{s.name}</strong><span className="tag">{s.snapshot.input_mode}</span><small>SHA-256 {s.sha256}</small><button onClick={()=>act(async()=>{setReadiness(await api(`/projects/${selected}/readiness?scenario_id=${s.id}`));setTab('Readiness');setNotice(`Audit of snapshot: ${s.name}`);})}>Review this snapshot →</button></div>)}</section><section className="panel form"><h2>Define a scenario</h2><p>Start and end times require UTC offsets. Add imported dataset IDs and documented initial/boundary conditions. Missing inputs may be saved for review; they cannot execute.</p><textarea aria-label="Scenario contract" value={scenario} spellCheck={false} onChange={e=>setScenario(e.target.value)}/><button className="primary" disabled={busy} onClick={()=>act(saveScenario)}>Save immutable snapshot</button></section></>}
 {tab==='Readiness'&&<><section className="panel"><div className="panel-heading"><h2>Inputs need review</h2><button disabled={busy} onClick={()=>act(async()=>{await api(`/projects/${selected}/readiness-jobs`,{method:'POST'});await refresh();setNotice('Project readiness audit queued. This is not a simulation.');})}>Run project audit</button></div>{readiness?.missing.map((i,k)=><div className="finding" key={k}><span className="finding-mark">!</span><div><strong>{i.code.replaceAll('_',' ')}</strong><p>{i.message}</p></div></div>)}{readiness?.warnings.map((i,k)=><div className="note" key={k}>{i.message}</div>)}</section><section className="panel"><h2>Audit jobs</h2>{!jobs.length?<p className="empty">No background audits yet.</p>:jobs.map(j=><div className="scenario" key={j.id}><span>{j.id}</span><strong>{j.state}</strong>{['QUEUED','RUNNING'].includes(j.state)&&<button onClick={()=>act(async()=>{await api(`/projects/${selected}/jobs/${j.id}/cancel`,{method:'POST'});await refresh();})}>Cancel audit</button>}<small>Execution state describes the audit job, not scientific validation.</small></div>)}</section></>}
 {tab==='Numerical runs'&&<><section className="panel"><h2>Engine examples</h2><p>These are laboratory or schematic examples from pinned solver sources. They do not predict flooding at Ujjani.</p>{health?.engines.map(e=><div className="scenario" key={e.engine}><strong>{e.engine==='dualsphysics'?'DualSPHysics CPU':'D-Flow FM'}</strong><span className="tag">{e.available?'IMAGE VERIFIED':'UNAVAILABLE'}</span><small>{e.available?e.image_id:e.reason}</small></div>)}{!project.synthetic?<button className="primary" disabled={busy} onClick={()=>act(openLaboratory)}>Open separate laboratory workspace</button>:<div className="form"><label>Engine<select aria-label="Numerical engine" value={engineChoice} onChange={e=>setEngineChoice(e.target.value as 'dualsphysics'|'dflowfm')}><option value="dualsphysics">DualSPHysics CPU · official dam-break example</option><option value="dflowfm">D-Flow FM · official sequential example</option></select></label><button className="primary" disabled={busy||!health?.engines.find(e=>e.engine===engineChoice)?.available} onClick={()=>act(submitNumerical)}>Queue official example</button><p>Jobs use bounded CPU, memory, output size and runtime. A successful solver exit still requires validated output normalization.</p></div>}</section><section className="panel"><h2>Run history</h2>{!runs.length?<p className="empty">No numerical runs in this project.</p>:runs.map(r=><div className="scenario" key={r.id}><strong>{r.input.request.engine} · {r.input.request.case_kind}</strong><span className="tag">{r.state}</span><small>{r.id}</small>{r.result.normalization&&<small>{r.result.normalization.frames} output times · {r.result.normalization.cells} cells · {r.result.normalization.duration_seconds.toFixed(3)} simulated seconds</small>}{(r.result.error||r.result.reason)&&<small>{r.result.error||r.result.reason}</small>}{['QUEUED','RUNNING'].includes(r.state)&&<button onClick={()=>act(async()=>{await api(`/projects/${selected}/runs/${r.id}/cancel`,{method:'POST'});await refresh();})}>Cancel run</button>}</div>)}</section><div className="note">Ujjani site scenarios and computed breach remain blocked pending verified mesh, hydraulic boundaries, reservoir information and method applicability.</div></>}
 </>}</div><footer>DamSafe / Ujjani–Bhima <span>Evidence status: unassessed</span></footer></main></div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
